spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_user?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 736100
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
      encoding: UTF-8
      continue-on-error: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

app:
  upload:
    user-root: ./data/uploads/user

management:
  endpoints:
    web:
      exposure:
        include: health,info

