server:
  port: 8087

spring:
  config:
    import:
      - 'optional:nacos:ecommerce-common.yaml?group=ECOMMERCE_DEV'
      - 'optional:nacos:ecommerce-order-service.yaml?group=ECOMMERCE_DEV'
  application:
    name: ecommerce-order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_order?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 736100
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: ecommerce
    password: ecommerce123
    listener:
      simple:
        default-requeue-rejected: false
  sql:
    init:
      mode: always
      continue-on-error: true
      encoding: UTF-8

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

app:
  mq:
    enabled: true
  redisson:
    mode: cluster
    cluster-nodes:
      - redis://localhost:7000
      - redis://localhost:7001
      - redis://localhost:7002
      - redis://localhost:7003
      - redis://localhost:7004
      - redis://localhost:7005
    single-server-address: redis://localhost:6379
    timeout: 3s
    connect-timeout: 3s
    lock-wait-time: 2s
    lock-lease-time: 10s
  order:
    pay-timeout-minutes: 10
    timeout-scan-enabled: false
  integration:
    inventory:
      service-id: ecommerce-inventory-service
      base-url: http://localhost:8086
    merchant:
      service-id: ecommerce-merchant-service
      base-url: http://localhost:8084
    user:
      service-id: ecommerce-user-service
      base-url: http://localhost:8083

management:
  endpoints:
    web:
      exposure:
        include: health,info


