services:
  redis-cluster:
    image: grokzen/redis-cluster:7.2.0
    container_name: redis-cluster-local
    restart: unless-stopped
    environment:
      IP: 127.0.0.1
      STANDALONE: "false"
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"

